theme = "doy"

[editor]
gutters = ["diagnostics", "diff"]
auto-info = false
color-modes = true

[keys.normal]
tab = ":w"
"|" = ":q"

"C-d" = ":buffer-close"

"ret" = "goto_definition"
"backspace" = "jump_backward"

[keys.normal.g]
j = "goto_last_line"
k = "goto_file_start"
