theme = "doy"

[editor]
gutters = ["diagnostics", "diff"]
auto-info = false
color-modes = true
true-color = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "⸽"

[keys.normal]
tab = ":w"
"|" = ":q"
"\\" = "shell_pipe"

"C-d" = ":buffer-close"

"ret" = "goto_definition"
"backspace" = "jump_backward"

[keys.normal.g]
j = "goto_last_line"
k = "goto_file_start"
