[[language]]
name = "rust"
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true }, diagnostics = { disabled = ["inactive-code"] } }

[[language]]
name = "python"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
