#!/bin/sh
set -eu
set -o pipefail

# key bindings
setxkbmap -option ctrl:nocaps
setxkbmap -option compose:caps
xmodmap "$HOME"/.Xmodmap
"$(dirname "$0")"/numkeys on

# trackpad settings
touchpad="$(xinput list --name-only | grep Touchpad)"
xinput set-prop "$touchpad" "libinput Accel Speed" 0.4
xinput set-prop "$touchpad" "libinput Tapping Enabled" 1

# needs to happen after xmodmap stuff
svre xcape
svre xbindkeys
