#!/bin/bash

confdir=$(dirname $0)
files="bash_logout
       bashrc
       crawlrc
       gtkrc
       inputrc
       nethackrc
       screenrc
       vimrc
       Xdefaults
       bin
       fortune
       vim"

function install() {
    if [[ -e "$2" && ! -h "$2" ]]; then
        mv "$2" "$2.bak"
    fi
    ln -sf "$confdir/$1" "$2"
}

for file in $files; do
    install "${file}" ".${file}"
done
