INSTALL := \
    .config/alacritty/alacritty.yml \
    .config/karabiner \
    .hammerspoon

EMPTYDIRS := \

INSTALL_CUSTOM := \

BUILD := \
    config/alacritty/alacritty.yml

config/alacritty/alacritty.yml : config/alacritty/alacritty.yml.st-doy1
	$(LN) $(notdir $<) $@
