INSTALL := \
    .config/alacritty/alacritty.yml \
    .config/karabiner \
    .hammerspoon \
    .skhdrc \
    .yabairc

EMPTYDIRS := \

INSTALL_CUSTOM := \

BUILD := \
    config/alacritty/alacritty.yml

config/alacritty/alacritty.yml : config/alacritty/alacritty.yml.st-doy2
	$(LN) $(notdir $<) $@
