#!/bin/sh
set -eu

podman images | grep -q localhost/reply || cat <<EOF | podman build -t reply -f -
FROM docker.io/debian:stable-slim
RUN sed -i 's/stable\/updates/stable-security\/updates/' /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends cpanminus make gcc libreadline-dev
RUN cpanm -n Reply B::Keywords Data::Dump Carp::Always Term::ReadLine::Gnu
EOF
podman run --rm -itv /home/doy/.replyrc:/root/.replyrc reply reply "$@"
