#!/bin/sh
set -eu

DOCKERFILE="$(cat <<EOF
FROM docker.io/debian:stable-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
  cpanminus \
  make \
  gcc \
  libreadline-dev
RUN cpanm -n Games::SMTNocturne::Demons
EOF
)"
IMAGE="$(basename "$0"):$(echo "$DOCKERFILE" | sha256sum | cut -d' ' -f1)"

if [ -z "$(podman images -q "$IMAGE")" ]; then
  echo "$DOCKERFILE" | podman build -t "$IMAGE" -f - .
fi

podman run --rm -it \
  "$IMAGE" \
  smt "$@"
