theme = "vim_dark_high_contrast"

[editor]
gutters = ["diagnostics", "diff"]
auto-info = false
color-modes = true
true-color = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "⸽"

[editor.lsp]
display-messages = true

[keys.normal]
tab = ":w"
"|" = ":q"
"\\" = "shell_pipe"

"C-d" = ":buffer-close"

"ret" = "goto_definition"
"backspace" = "jump_backward"

[keys.normal.space]
o = ":diffg"
