"ui.background" = { bg = "black" }
"ui.cursor" = { fg = "green", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "light-green", modifiers = ["reversed"] }
"ui.cursor.select" = { fg = "green", modifiers = ["reversed"] }
"ui.menu" = { fg = "white", bg = "dark-black" }
"ui.menu.selected" = { fg = "yellow" }
"ui.popup" = { bg = "dark-black" }
"ui.selection" = { bg = "dark-white" }
"ui.statusline" = { fg = "light-green", bg = "dark-magenta" }
"ui.statusline.normal" = { fg = "black", bg = "light-yellow" }
"ui.statusline.insert" = { fg = "black", bg = "light-cyan" }
"ui.statusline.select" = { fg = "black", bg = "yellow" }
"ui.text" = { fg = "white" }
"ui.text.info" = { fg = "white", bg = "red" }
"ui.text.focus" = { fg = "yellow" }
"special" = { fg = "cyan" }

"diagnostic.error" = { bg = "#330000" }
"diagnostic.warning" = { bg = "#333300" }
"diagnostic.hint" = { bg = "#003333" }
"diagnostic.info" = { bg = "#330033" }
"warning" = { fg = "yellow", bg = "dark-yellow" }
"error" = { fg = "red", bg = "dark-red" }
"info" = { fg = "white", bg = "dark-white" }
"hint" = { fg = "cyan", bg = "dark-cyan" }

"type" = "green"
"constructor" = "light-cyan"
"constant" = "red"
"constant.character.escape" = "magenta"
"string" = "red"
"comment" = "light-black"
"comment.documentation" = "magenta"
"label" = "green"
"keyword" = "yellow"
"keyword.directive" = "magenta"
"function" = "light-cyan"
"function.macro" = "magenta"

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

[palette]
black = "#000000"
red = "#ed5f74"
green = "#1ea672"
yellow = "#d97917"
blue = "#688ef1"
magenta = "#c96ed0"
cyan = "#3a97d4"
white = "#e3e8ee"
light-black = "#697386"
light-red = "#fbb5b2"
light-green = "#85d996"
light-yellow = "#efc078"
light-blue = "#9fcdff"
light-magenta = "#f0b4e4"
light-cyan = "#7fd3ed"
light-white = "#ffffff"
dark-black = "#273141"
dark-red = "#541e20"
dark-green = "#003c04"
dark-yellow = "#482900"
dark-blue = "#00355c"
dark-magenta = "#4e1d47"
dark-cyan = "#00394f"
dark-white = "#303030"
