#!/usr/bin/env python3

from datetime import datetime, timedelta, timezone
import sqlite3
import sys
from time import sleep
import traceback
from typing import Callable, TypeVar

from aranet4 import client

NOW = datetime.today()

DDL = """
    CREATE TABLE IF NOT EXISTS readings (
        date INTEGER UNIQUE PRIMARY KEY,
        co2 INTEGER,
        temp INTEGER,
        humid INTEGER,
        pressure INTEGER
    );
    CREATE TABLE IF NOT EXISTS battery (
        date INTEGER UNIQUE PRIMARY KEY,
        battery INTEGER
    );
"""

T = TypeVar("T")


class Db:
    def __init__(self, db_name: str):
        self.con = sqlite3.connect(db_name)
        self.con.autocommit = False

    def init_ddl(self):
        with self.con:
            self.con.executescript(DDL)

    def latest_reading(self):
        with self.con:
            res = self.con.execute("SELECT max(date) FROM readings")
        row = res.fetchone()
        if row is None or row[0] is None:
            return None
        return datetime.fromtimestamp(row[0], timezone.utc)

    def insert_readings(self, values: list[tuple[int, int, int, int, int]]):
        with self.con:
            self.con.executemany(
                "INSERT OR IGNORE INTO readings VALUES (?, ?, ?, ?, ?)",
                values,
            )

    def insert_battery(self, value: int):
        with self.con:
            self.con.execute(
                "INSERT INTO battery VALUES (?, ?)",
                (int(NOW.timestamp()), value),
            )

    def changes(self):
        return self.con.total_changes


def retry(f: Callable[[], T], n: int) -> T:
    for i in range(n):
        try:
            return f()
        except:
            if i == n - 1:
                raise
            else:
                print(f"attempt {i + 1} failed, retrying:", file=sys.stderr)
                traceback.print_exc()
        sleep(1)
    raise RuntimeError("unreachable")


def main():
    mac = sys.argv[1]
    db_name = sys.argv[2]

    db = Db(db_name)
    db.init_ddl()
    latest = db.latest_reading()
    filter = {}
    if latest is not None:
        filter["start"] = latest - timedelta(hours=1)

    history = retry(lambda: client.get_all_records(mac, filter), 5)
    rows = [
        (
            int(record.date.timestamp()),  # type: ignore
            int(record.co2),
            int(record.temperature * 10),
            int(record.humidity),
            int(record.pressure * 10),
        )
        for record in history.value
        if record.co2 >= 0
        and record.temperature >= 0
        and record.humidity >= 0
        and record.pressure >= 0
    ]
    db.insert_readings(rows)
    print(f"inserted {db.changes()} rows")

    current = retry(lambda: client.get_current_readings(mac), 5)
    db.insert_battery(current.battery)
    print(f"current battery: {current.battery}")


if __name__ == "__main__":
    main()
