#!/bin/sh

pr_num="$1"
upstream="${2-origin}"
git fetch "$upstream" "pull/${pr_num}/head:pull-${pr_num}"
if [ -d "$(git root)/.jj" ]; then
  ref=$(git name-rev --name-only --refs='remotes/*' "pull-${pr_num}")
  remote="${ref%%/*}"
  branch="${ref#*/}"
  jj bookmark track "${branch}@${remote}"
fi
