[package]
name = "picker"
version = "0.1.0"
edition = "2021"

[dependencies]
owo-colors = "3.5.0"
nucleo-matcher = "0.3.1"
serde = "1.0.217"
serde_json = "1.0.134"
unicode-width = "0.1.14"
zellij-tile = "0.41.1"
