#!/bin/sh

services=""
trap 'for service in $services; do systemctl --user start $service; done' EXIT
for service in unclutter picom; do
    if [ "$(systemctl --user show --property MainPID --value "$service")" != 0 ]; then
        systemctl --user stop "$service"
        services="$service $services"
    fi
done
/usr/bin/import "$@"
