[window]
width = 200
height = 200
padding = 60
spacing = 20
margin_horiz = { anchor = "Right", margin = 980 }
margin_vert = { anchor = "Top", margin = 575 }
duration = 1200
opacity = 70

[percentage]
show_numeric = true

[boolean]
show_label = true
